// <auto-generated />
using System;
using AgendaApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendaApp.Migrations
{
    [DbContext(typeof(AgendaContext))]
    partial class AgendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Lib.Classes.Entities.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("DATE");

                    b.Property<int>("IntervaloId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Dia")
                        .HasDatabaseName("IX_Agenda_Dia");

                    b.HasIndex("IntervaloId")
                        .IsUnique();

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("Lib.Classes.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Lib.Classes.Entities.Intervalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comeco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IndexAula")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IndexAula")
                        .IsUnique()
                        .HasDatabaseName("IX_Intervalo_IndexAula");

                    b.ToTable("Intervalos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comeco = "08:05",
                            IndexAula = 0,
                            Label = "1º Aula"
                        },
                        new
                        {
                            Id = 2,
                            Comeco = "08:55",
                            IndexAula = 1,
                            Label = "2º Aula"
                        },
                        new
                        {
                            Id = 3,
                            Comeco = "10:00",
                            IndexAula = 2,
                            Label = "3º Aula"
                        },
                        new
                        {
                            Id = 4,
                            Comeco = "10:50",
                            IndexAula = 3,
                            Label = "4º Aula"
                        },
                        new
                        {
                            Id = 5,
                            Comeco = "13:05",
                            IndexAula = 4,
                            Label = "1º Aula"
                        },
                        new
                        {
                            Id = 6,
                            Comeco = "13:55",
                            IndexAula = 5,
                            Label = "2º Aula"
                        },
                        new
                        {
                            Id = 7,
                            Comeco = "14:45",
                            IndexAula = 6,
                            Label = "3º Aula"
                        },
                        new
                        {
                            Id = 8,
                            Comeco = "15:50",
                            IndexAula = 7,
                            Label = "4º Aula"
                        },
                        new
                        {
                            Id = 9,
                            Comeco = "16:40",
                            IndexAula = 8,
                            Label = "5º Aula"
                        },
                        new
                        {
                            Id = 10,
                            Comeco = "19:00",
                            IndexAula = 9,
                            Label = "1º Aula"
                        },
                        new
                        {
                            Id = 11,
                            Comeco = "19:50",
                            IndexAula = 10,
                            Label = "2º Aula"
                        },
                        new
                        {
                            Id = 12,
                            Comeco = "22:55",
                            IndexAula = 11,
                            Label = "3º Aula"
                        },
                        new
                        {
                            Id = 13,
                            Comeco = "21:45",
                            IndexAula = 12,
                            Label = "4º Aula"
                        });
                });

            modelBuilder.Entity("Lib.Classes.Entities.Agenda", b =>
                {
                    b.HasOne("Lib.Classes.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("Lib.Classes.Entities.Intervalo", "Intervalo")
                        .WithOne()
                        .HasForeignKey("Lib.Classes.Entities.Agenda", "IntervaloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Intervalo");
                });
#pragma warning restore 612, 618
        }
    }
}
